# Assignment-3 {Q-1}

In [13]:
import pandas as pd
import scipy 
import numpy as np
from scipy import stats

In [14]:
ls

 Volume in drive C is OS
 Volume Serial Number is 267A-0770

 Directory of C:\Users\HP\Ass-3 Hypothesis Testing

07-07-2022  01:23    <DIR>          .
07-07-2022  01:23    <DIR>          ..
06-07-2022  19:33    <DIR>          .ipynb_checkpoints
07-07-2022  01:23             6,798 Ass_3_Hypothesis_Testing.ipynb
30-06-2022  00:22                87 BuyerRatio.csv
30-06-2022  00:22            13,423 Costomer+OrderForm.csv
30-06-2022  00:22               525 Cutlets.csv
30-06-2022  00:22             3,487 LabTAT.csv
               5 File(s)         24,320 bytes
               3 Dir(s)  51,284,135,936 bytes free


In [15]:
data = pd.read_csv("Cutlets.csv")

In [16]:
data.head(5)

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Unit A  35 non-null     float64
 1   Unit B  35 non-null     float64
dtypes: float64(2)
memory usage: 688.0 bytes


In [18]:
unitA = pd.Series(data.iloc[:,0])
unitA.head(5)

0    6.8090
1    6.4376
2    6.9157
3    7.3012
4    7.4488
Name: Unit A, dtype: float64

In [19]:
unitB = pd.Series(data.iloc[:,1])
unitB.head(5)

0    6.7703
1    7.5093
2    6.7300
3    6.7878
4    7.1522
Name: Unit B, dtype: float64

In [34]:
p_value = stats.ttest_ind(unitA,unitB)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.47223947245995)

In [33]:
p_value[1]


0.47223947245995

So the Pvalue is more than the significance alpha =5% ie 0.05 so the Null Hypothesis of the problem is true
that there is a diffrence in size of the cutlets of the two units.

# Assignment-3 {Q-2}

In [35]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [36]:
ls

 Volume in drive C is OS
 Volume Serial Number is 267A-0770

 Directory of C:\Users\HP\Ass-3 Hypothesis Testing

07-07-2022  01:33    <DIR>          .
07-07-2022  01:33    <DIR>          ..
06-07-2022  19:33    <DIR>          .ipynb_checkpoints
07-07-2022  01:33             6,973 Ass_3_Hypothesis_Testing.ipynb
30-06-2022  00:22                87 BuyerRatio.csv
30-06-2022  00:22            13,423 Costomer+OrderForm.csv
30-06-2022  00:22               525 Cutlets.csv
30-06-2022  00:22             3,487 LabTAT.csv
               5 File(s)         24,495 bytes
               3 Dir(s)  51,280,306,176 bytes free


In [37]:
lab = pd.read_csv("LabTAT.csv")

In [38]:
lab.head(5)

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [39]:
lab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laboratory 1  120 non-null    float64
 1   Laboratory 2  120 non-null    float64
 2   Laboratory 3  120 non-null    float64
 3   Laboratory 4  120 non-null    float64
dtypes: float64(4)
memory usage: 3.9 KB


In [41]:
pvalue_lab = stats.f_oneway(lab.iloc[:,0],lab.iloc[:,1],lab.iloc[:,2],lab.iloc[:,3])
pvalue_lab

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [45]:
pvalue_lab[1]

2.1156708949992414e-57

On comparing the p-value of the test by 5% significance alpha, the pvalue is less so the Null Hypothesis that there is diffrence in Lab TAT result time is False.

# Assignment-3 {Q-3}


In [145]:
from scipy.stats import chi2_contingency,chi2
import numpy as np  

In [146]:
ls


 Volume in drive C is OS
 Volume Serial Number is 267A-0770

 Directory of C:\Users\HP\Ass-3 Hypothesis Testing

07-07-2022  02:37    <DIR>          .
07-07-2022  02:37    <DIR>          ..
06-07-2022  19:33    <DIR>          .ipynb_checkpoints
07-07-2022  02:37            30,058 Ass_3_Hypothesis_Testing.ipynb
30-06-2022  00:22                87 BuyerRatio.csv
30-06-2022  00:22            13,423 Costomer+OrderForm.csv
30-06-2022  00:22               525 Cutlets.csv
30-06-2022  00:22             3,487 LabTAT.csv
               5 File(s)         47,580 bytes
               3 Dir(s)  51,276,185,600 bytes free


In [147]:
df = pd.read_csv("BuyerRatio.csv")

In [148]:
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [149]:
data = df.iloc[:,1:5]

In [150]:
data

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [151]:
data.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [152]:
exp = stats.chi2_contingency(data)
exp

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [153]:
expected = exp[3]

In [154]:
rows=len(data.iloc[0:2,0])
columns=len(data.iloc[0,0:4])
dof=(rows-1)*(columns-1)
print('Degree of Freedom=',dof)

Degree of Freedom= 3


In [155]:
o = data.values
e = expected

In [156]:
 chi_square = chisquare(o,e,ddof=3)
chi_square

Power_divergenceResult(statistic=array([1.34226039e+00, 1.73035255e-01, 1.15612650e-04, 8.05342809e-02]), pvalue=array([nan, nan, nan, nan]))

In [157]:
Statistics= sum(chi_square[0])
Statistics

1.5959455386610577

In [158]:
pvalue = 1-chi2.cdf(Statistics,3)
pvalue

0.6603094907091882

In [159]:
if pvalue <= 0.05:
    print("Null Hypothesis False - All proportions are not equal.")
else:
    print("Null Hypothesis True -  All propotions are equal.")

Null Hypothesis True -  All propotions are equal.


# Assignment-3 {Q-4}

In [160]:
from scipy.stats import chi2_contingency,chi2
import numpy as np

In [161]:
ls


 Volume in drive C is OS
 Volume Serial Number is 267A-0770

 Directory of C:\Users\HP\Ass-3 Hypothesis Testing

07-07-2022  02:37    <DIR>          .
07-07-2022  02:37    <DIR>          ..
06-07-2022  19:33    <DIR>          .ipynb_checkpoints
07-07-2022  02:37            30,058 Ass_3_Hypothesis_Testing.ipynb
30-06-2022  00:22                87 BuyerRatio.csv
30-06-2022  00:22            13,423 Costomer+OrderForm.csv
30-06-2022  00:22               525 Cutlets.csv
30-06-2022  00:22             3,487 LabTAT.csv
               5 File(s)         47,580 bytes
               3 Dir(s)  51,276,251,136 bytes free


In [162]:
data = pd.read_csv("Costomer+OrderForm.csv")
data.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [163]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB


In [164]:
data.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [165]:
data.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [166]:
data.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [167]:
data.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [168]:
o = np.array([[271,267,269,280],[29,33,31,20]])

In [169]:
o

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [170]:
expected = chi2_contingency(o)
expected

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [171]:
e = expected[3]
e

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [172]:
rows=len(data.iloc[0:300,0])
columns=len(data.iloc[0,0:4])
dof=(rows-1)*(columns-1)
print('Degree of Freedom=',dof)

Degree of Freedom= 897


In [174]:
chi_square = chisquare(o,e,ddof=897)
chi_square

Power_divergenceResult(statistic=array([0.02198142, 0.88169925, 0.295528  , 2.65975202]), pvalue=array([nan, nan, nan, nan]))

In [176]:
statistics = sum(chi_square[0])
statistics

3.8589606858203545

In [178]:
pvalue = 1-chi2.cdf(statistics,897)
pvalue

1.0

In [179]:
if pvalue <= 0.05:
    print("Null Hypothesis False -  Defective % not varies by center.")
else:
    print("Null Hypothesis True -  Defective % varies by center.")

Null Hypothesis True -  Defective % varies by center.
